var cancel=document.querySelector(".after-click i"); // cancel button 
var after_div=document.querySelector(".after-click"); //div where the cookie text will gonna appear
var p=document.querySelector(".text p");
var cookie1=document.querySelector(".cookie1 img");
var cookie_div1=document.querySelector(".cookie1");

var cookie2=document.querySelector(".cookie2 img");
var cookie_div2=document.querySelector(".cookie2");

var cookie3=document.querySelector(".cookie3 img");
var cookie_div3=document.querySelector(".cookie3");

cookie1.addEventListener("click",()=>{
    var num=Math.floor(Math.random() * 116) + 1;
    var list=['A strong individual is conqueror of its mind.','Suffering is more often imagined than what reality brings you.','Man is what he thinks all day long.','You have power over your mind - not outside events. Realize this, and you will find strength.','Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.','Waste no more time arguing about what a good person should be. Be one.','Death smiles at us all, but all a person can do is smile back.','Very little is needed to make a happy life; it is all within yourself, in your way of thinking.','The soul becomes dyed with the colour of its thoughts','When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.','Your love for yourself is superior to other people, so why do you care more about other’s opinions than your own?','Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.','Be the change you want to see in the world.','Experience is the teacher of all things.'
,'There is nothing impossible to him who will try.','Convert every disaster into an opportunity.','No person will make a great leader who wants to do it all itself, or to get all the credit for doing it.','A person always has two reasons for doing anything: a good reason and the real reason.','Go as far as you can see; when you get there, you\'ll be able to see farther.','The first step towards getting somewhere is to decide that you are not going to stay where you are.','If you think you can do a thing or think you can\'t do a thing, you\'re right.','Failure is simply the opportunity to begin again, this time more intelligently.','Quality means doing it right when no one is looking.','Don\'t find fault, find a remedy.','Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young.','Obstacles are those frightful things you see when you take your eyes off your goal.','You have not failed, you simply found 10,000 ways that won\'t work.','Many of life\'s failures are people who did not realize how close they were to success when they gave up.','Opportunity is missed by most people because it is dressed in overalls and looks like work.','The richest person is not the one who has the most but the one that needs the less.','We motivate to do something when we accept what is necessary to achieve it.','It\'s not what you know, but the questions you ask.'
,'We are only limited by the scope of our vision and our willingness to take risks.','Find something you want to die for, and then live for it.','Great minds talk about ideas,Average minds talk about events,Small minds talk about people.','Money is a vehicle for growth, not an impression mechanism.','The poor plays to avoid losing, the rich plays to win.','A loser avoids failure at all costs, but failure is what makes a winner.','It is not about what you sell but how you sell it.','Money is the universal criteria by whom success is measured.','Never hate your enemies, it affects your judgment.','Friendship and money: Oil and water.','If you always do what you\’ve always done,You\’ll always get what you\’ve always got.','Shortcuts don\'t equal permanent results.','If you want what you’ve never had, you must do what you’ve never done.'
,'Remember, today is the tomorrow you worried about yesterday.','The only way to get the best of an argument is to avoid it.','You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.','If you want to gather honey, don\'t kick over the beehive.','It isn\'t what you have, or who you are, or where you are, or what you are doing that makes you happy or unhappy. It is what you think about.','Success is getting what you want. Happiness is wanting what you get.','Any fool can criticize, condemn, and complain but it takes character and self control to be understanding and forgiving.','Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.','Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.','When a man is generous, he must show his generosity as personal.','When negotiating; never get angry. Never make a threat, rather reason, even if it means swallowing insults.','Never take your words at a sentimental value when facing your opponent.','Break the chains of your thought in order to break the chains of your body.','Releasing anger without forethought is the most dangerous indulgence; releasing threats is a foolish kind of exposure.','Have your enemy overestimate your faults and your friend underestimate your virtues.','Time erodes gratitude more quickly than it does beauty.','Concentration is the root to all of higher abilities of men.','Accepting something does not mean passive resignation.','Stress comes from ignoring things that you shouldn\’t be ignoring.',
,'The pessimist complains over the wind.The optimist expects it to change.The realist adjusts the sails.','Don\'t criticize, for what you critic is what you may be under similar circumstances.','When dealing with an individual, you are not dealing with a person of logic but rather emotion; motivated by pride and vanity.','God himself does not propose to judge a man until the end of his days, why should you and I?','It\'s better to do something in a day with no dream than to dream and do nothing at all.','Don\'t be afraid of enemies who attack you, be afraid of friends who flatter you.','Flattery is precisely telling the other person what he thinks about himself.','Learn to distinguish between petty flattery and appreciation.','The desire to be important is the deepest urge of human nature.','Talk to people about themselves and they will listen for hours.','A victory over an argument is an empty victory because you will never get your opponents good will.','Anyone who disagrees with you is interested in the same things you are.','How you deploy your attention determines your reality.','Self-mastery comes from learning how to delay gratification in pursuit of your goals.','The ability to notice that we are getting anxious and to take steps to renew our focus rests on self-awareness.','There are no side effects in a system, only effects. What we call side effects is just a reflect of a flawed understanding of the system.','A flood of data can either trigger a "Eureka!" moment or an overload of information.','For a long term change you require consistent positive action.',
'Focus on the negatives; offers a recipe for depression. ','If everything worked out perfectly in your life, what would you be doing in 10 years?','The concentration area in your brain is like a muscle; breathe and be aware of every breath, once you wonder off in thoughts and notice, come back to the breath. Every time you notice you’ve wandered off and came back; will be the equivalent of a rep in lifting a weight.','A focus on our strengths, urges us toward a desired future and stimulates openness to new ideas, people and plans. In contrast, spotlighting our weaknesses elicits a defensive sense of obligation and guilt, closing us down.','You need negative focus to survive, but a positive to thrive.','Anxiety associated with punishment hampers the prefrontal cortex while trying to concentrate and learn, creating further impediment for improvement.','The core elements of smart practise rely on a combination of joy, tactics and full focus.','Mindfulness of the future means taking into account the consequences of our actions.','To tell a good story; is to grab and keep someone\’s attention.','Leader example - "We don\'t hire to make… we make to hire"','In the service of what am I using the talents I have?','Anger builds on anger; the highest level becomes a point of violence becoming unforgiving and beyond reasoned with. The thoughts revolve on revenge or reprisal, oblivious to what the consequence must be.','Disable your angry opponent before reaching a cognitive incapacitation. ',
'During anger you must not suppress it. But don\'t act on it.','Setting the emotional tone of an interaction means a sign of dominance, it is why emotional entertainment  is the heart of influence.','The greatest things are accomplished by silence - not in the clamor or display of superficial eventfulness, but in the deep clarity of inner vision.','Sometimes it seems that our many words are more an expression of our doubt than our faith.','When the lord is accused he keeps silent. He has no need of defence. Those who defend themselves  are those who fear being defeated.','Speak only when it is more useful to speak than to be silent.','A bitter ending is better than an endless bitterness.','Its not about how hard you hit, its about how hard you get hit and still moving forward.','Only the <b>disciplined</b> ones are free in life. If you aren\'t <b>disciplined</b>, you are a slave to your moods. You are a slave to your passions.','It is only by becoming aware of our vulnerability to social pressure that we can begin to build resistance to conformity when it is not in our best interest to yield to the mentality of the herd.','Nearly all men can stand adversity, but if you want to test a man\’s character, give him power.','Kindness can be more than its own reward.','The power of a situation and the behaviour imposed by a system determines a social context.',
'Every exit is an entrance somewhere else.','Those who have a "why" can bare any "how"','The price of anything is the amount of life you exchange for it.','The law never to be broken is never to be required.','Everyone reacts and therefor consequentially acts to the form they deem most convenient based on their knowledge from life experience, therefor I cannot judge for something I would have comited if placed under the same circumstances of life and its obstacles.','Aim to be the person at your father\'s funeral that everyone, in their grief and misery, can rely on.','The devil learns more from experience than from intellect'

    ]

    cookie1.style.display="none";
var inner_div=document.createElement('div');
var text=document.createElement("p");
text.classList+="innertext"
text.innerHTML=list[num];
console.log(list.length);

inner_div.appendChild(text);
inner_div.classList+="inner-div";
cookie_div1.appendChild(inner_div);    
})



cookie2.addEventListener("click",()=>{
    var num=Math.floor(Math.random() * 116) + 1;
    var list=['A strong individual is conqueror of its mind.','Suffering is more often imagined than what reality brings you.','Man is what he thinks all day long.','You have power over your mind - not outside events. Realize this, and you will find strength.','Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.','Waste no more time arguing about what a good person should be. Be one.','Death smiles at us all, but all a person can do is smile back.','Very little is needed to make a happy life; it is all within yourself, in your way of thinking.','The soul becomes dyed with the colour of its thoughts','When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.','Your love for yourself is superior to other people, so why do you care more about other’s opinions than your own?','Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.','Be the change you want to see in the world.','Experience is the teacher of all things.'
,'There is nothing impossible to him who will try.','Convert every disaster into an opportunity.','No person will make a great leader who wants to do it all itself, or to get all the credit for doing it.','A person always has two reasons for doing anything: a good reason and the real reason.','Go as far as you can see; when you get there, you\'ll be able to see farther.','The first step towards getting somewhere is to decide that you are not going to stay where you are.','If you think you can do a thing or think you can\'t do a thing, you\'re right.','Failure is simply the opportunity to begin again, this time more intelligently.','Quality means doing it right when no one is looking.','Don\'t find fault, find a remedy.','Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young.','Obstacles are those frightful things you see when you take your eyes off your goal.','You have not failed, you simply found 10,000 ways that won\'t work.','Many of life\'s failures are people who did not realize how close they were to success when they gave up.','Opportunity is missed by most people because it is dressed in overalls and looks like work.','The richest person is not the one who has the most but the one that needs the less.','We motivate to do something when we accept what is necessary to achieve it.','It\'s not what you know, but the questions you ask.'
,'We are only limited by the scope of our vision and our willingness to take risks.','Find something you want to die for, and then live for it.','Great minds talk about ideas,Average minds talk about events,Small minds talk about people.','Money is a vehicle for growth, not an impression mechanism.','The poor plays to avoid losing, the rich plays to win.','A loser avoids failure at all costs, but failure is what makes a winner.','It is not about what you sell but how you sell it.','Money is the universal criteria by whom success is measured.','Never hate your enemies, it affects your judgment.','Friendship and money: Oil and water.','If you always do what you\’ve always done,You\’ll always get what you\’ve always got.','Shortcuts don\'t equal permanent results.','If you want what you’ve never had, you must do what you’ve never done.'
,'Remember, today is the tomorrow you worried about yesterday.','The only way to get the best of an argument is to avoid it.','You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.','If you want to gather honey, don\'t kick over the beehive.','It isn\'t what you have, or who you are, or where you are, or what you are doing that makes you happy or unhappy. It is what you think about.','Success is getting what you want. Happiness is wanting what you get.','Any fool can criticize, condemn, and complain but it takes character and self control to be understanding and forgiving.','Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.','Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.','When a man is generous, he must show his generosity as personal.','When negotiating; never get angry. Never make a threat, rather reason, even if it means swallowing insults.','Never take your words at a sentimental value when facing your opponent.','Break the chains of your thought in order to break the chains of your body.','Releasing anger without forethought is the most dangerous indulgence; releasing threats is a foolish kind of exposure.','Have your enemy overestimate your faults and your friend underestimate your virtues.','Time erodes gratitude more quickly than it does beauty.','Concentration is the root to all of higher abilities of men.','Accepting something does not mean passive resignation.','Stress comes from ignoring things that you shouldn\’t be ignoring.',
,'The pessimist complains over the wind.The optimist expects it to change.The realist adjusts the sails.','Don\'t criticize, for what you critic is what you may be under similar circumstances.','When dealing with an individual, you are not dealing with a person of logic but rather emotion; motivated by pride and vanity.','God himself does not propose to judge a man until the end of his days, why should you and I?','It\'s better to do something in a day with no dream than to dream and do nothing at all.','Don\'t be afraid of enemies who attack you, be afraid of friends who flatter you.','Flattery is precisely telling the other person what he thinks about himself.','Learn to distinguish between petty flattery and appreciation.','The desire to be important is the deepest urge of human nature.','Talk to people about themselves and they will listen for hours.','A victory over an argument is an empty victory because you will never get your opponents good will.','Anyone who disagrees with you is interested in the same things you are.','How you deploy your attention determines your reality.','Self-mastery comes from learning how to delay gratification in pursuit of your goals.','The ability to notice that we are getting anxious and to take steps to renew our focus rests on self-awareness.','There are no side effects in a system, only effects. What we call side effects is just a reflect of a flawed understanding of the system.','A flood of data can either trigger a "Eureka!" moment or an overload of information.','For a long term change you require consistent positive action.',
'Focus on the negatives; offers a recipe for depression. ','If everything worked out perfectly in your life, what would you be doing in 10 years?','The concentration area in your brain is like a muscle; breathe and be aware of every breath, once you wonder off in thoughts and notice, come back to the breath. Every time you notice you’ve wandered off and came back; will be the equivalent of a rep in lifting a weight.','A focus on our strengths, urges us toward a desired future and stimulates openness to new ideas, people and plans. In contrast, spotlighting our weaknesses elicits a defensive sense of obligation and guilt, closing us down.','You need negative focus to survive, but a positive to thrive.','Anxiety associated with punishment hampers the prefrontal cortex while trying to concentrate and learn, creating further impediment for improvement.','The core elements of smart practise rely on a combination of joy, tactics and full focus.','Mindfulness of the future means taking into account the consequences of our actions.','To tell a good story; is to grab and keep someone\’s attention.','Leader example - "We don\'t hire to make… we make to hire"','In the service of what am I using the talents I have?','Anger builds on anger; the highest level becomes a point of violence becoming unforgiving and beyond reasoned with. The thoughts revolve on revenge or reprisal, oblivious to what the consequence must be.','Disable your angry opponent before reaching a cognitive incapacitation. ',
'During anger you must not suppress it. But don\'t act on it.','Setting the emotional tone of an interaction means a sign of dominance, it is why emotional entertainment  is the heart of influence.','The greatest things are accomplished by silence - not in the clamor or display of superficial eventfulness, but in the deep clarity of inner vision.','Sometimes it seems that our many words are more an expression of our doubt than our faith.','When the lord is accused he keeps silent. He has no need of defence. Those who defend themselves  are those who fear being defeated.','Speak only when it is more useful to speak than to be silent.','A bitter ending is better than an endless bitterness.','Its not about how hard you hit, its about how hard you get hit and still moving forward.','Only the <b>disciplined</b> ones are free in life. If you aren\'t <b>disciplined</b>, you are a slave to your moods. You are a slave to your passions.','It is only by becoming aware of our vulnerability to social pressure that we can begin to build resistance to conformity when it is not in our best interest to yield to the mentality of the herd.','Nearly all men can stand adversity, but if you want to test a man\’s character, give him power.','Kindness can be more than its own reward.','The power of a situation and the behaviour imposed by a system determines a social context.',
'Every exit is an entrance somewhere else.','Those who have a "why" can bare any "how"','The price of anything is the amount of life you exchange for it.','The law never to be broken is never to be required.','Everyone reacts and therefor consequentially acts to the form they deem most convenient based on their knowledge from life experience, therefor I cannot judge for something I would have comited if placed under the same circumstances of life and its obstacles.','Aim to be the person at your father\'s funeral that everyone, in their grief and misery, can rely on.','The devil learns more from experience than from intellect'

    ]

    cookie2.style.display="none";
var inner_div=document.createElement('div');
var text=document.createElement("p");
text.classList+="innertext"
text.innerHTML=list[num];
console.log(list.length);

inner_div.appendChild(text);
inner_div.classList+="inner-div";
cookie_div2.appendChild(inner_div);    
})


cookie3.addEventListener("click",()=>{
    var num=Math.floor(Math.random() * 116) + 1;
    var list=['A strong individual is conqueror of its mind.','Suffering is more often imagined than what reality brings you.','Man is what he thinks all day long.','You have power over your mind - not outside events. Realize this, and you will find strength.','Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.','Waste no more time arguing about what a good person should be. Be one.','Death smiles at us all, but all a person can do is smile back.','Very little is needed to make a happy life; it is all within yourself, in your way of thinking.','The soul becomes dyed with the colour of its thoughts','When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.','Your love for yourself is superior to other people, so why do you care more about other’s opinions than your own?','Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.','Be the change you want to see in the world.','Experience is the teacher of all things.'
,'There is nothing impossible to him who will try.','Convert every disaster into an opportunity.','No person will make a great leader who wants to do it all itself, or to get all the credit for doing it.','A person always has two reasons for doing anything: a good reason and the real reason.','Go as far as you can see; when you get there, you\'ll be able to see farther.','The first step towards getting somewhere is to decide that you are not going to stay where you are.','If you think you can do a thing or think you can\'t do a thing, you\'re right.','Failure is simply the opportunity to begin again, this time more intelligently.','Quality means doing it right when no one is looking.','Don\'t find fault, find a remedy.','Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young.','Obstacles are those frightful things you see when you take your eyes off your goal.','You have not failed, you simply found 10,000 ways that won\'t work.','Many of life\'s failures are people who did not realize how close they were to success when they gave up.','Opportunity is missed by most people because it is dressed in overalls and looks like work.','The richest person is not the one who has the most but the one that needs the less.','We motivate to do something when we accept what is necessary to achieve it.','It\'s not what you know, but the questions you ask.'
,'We are only limited by the scope of our vision and our willingness to take risks.','Find something you want to die for, and then live for it.','Great minds talk about ideas,Average minds talk about events,Small minds talk about people.','Money is a vehicle for growth, not an impression mechanism.','The poor plays to avoid losing, the rich plays to win.','A loser avoids failure at all costs, but failure is what makes a winner.','It is not about what you sell but how you sell it.','Money is the universal criteria by whom success is measured.','Never hate your enemies, it affects your judgment.','Friendship and money: Oil and water.','If you always do what you\’ve always done,You\’ll always get what you\’ve always got.','Shortcuts don\'t equal permanent results.','If you want what you’ve never had, you must do what you’ve never done.'
,'Remember, today is the tomorrow you worried about yesterday.','The only way to get the best of an argument is to avoid it.','You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.','If you want to gather honey, don\'t kick over the beehive.','It isn\'t what you have, or who you are, or where you are, or what you are doing that makes you happy or unhappy. It is what you think about.','Success is getting what you want. Happiness is wanting what you get.','Any fool can criticize, condemn, and complain but it takes character and self control to be understanding and forgiving.','Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.','Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.','When a man is generous, he must show his generosity as personal.','When negotiating; never get angry. Never make a threat, rather reason, even if it means swallowing insults.','Never take your words at a sentimental value when facing your opponent.','Break the chains of your thought in order to break the chains of your body.','Releasing anger without forethought is the most dangerous indulgence; releasing threats is a foolish kind of exposure.','Have your enemy overestimate your faults and your friend underestimate your virtues.','Time erodes gratitude more quickly than it does beauty.','Concentration is the root to all of higher abilities of men.','Accepting something does not mean passive resignation.','Stress comes from ignoring things that you shouldn\’t be ignoring.',
,'The pessimist complains over the wind.The optimist expects it to change.The realist adjusts the sails.','Don\'t criticize, for what you critic is what you may be under similar circumstances.','When dealing with an individual, you are not dealing with a person of logic but rather emotion; motivated by pride and vanity.','God himself does not propose to judge a man until the end of his days, why should you and I?','It\'s better to do something in a day with no dream than to dream and do nothing at all.','Don\'t be afraid of enemies who attack you, be afraid of friends who flatter you.','Flattery is precisely telling the other person what he thinks about himself.','Learn to distinguish between petty flattery and appreciation.','The desire to be important is the deepest urge of human nature.','Talk to people about themselves and they will listen for hours.','A victory over an argument is an empty victory because you will never get your opponents good will.','Anyone who disagrees with you is interested in the same things you are.','How you deploy your attention determines your reality.','Self-mastery comes from learning how to delay gratification in pursuit of your goals.','The ability to notice that we are getting anxious and to take steps to renew our focus rests on self-awareness.','There are no side effects in a system, only effects. What we call side effects is just a reflect of a flawed understanding of the system.','A flood of data can either trigger a "Eureka!" moment or an overload of information.','For a long term change you require consistent positive action.',
'Focus on the negatives; offers a recipe for depression. ','If everything worked out perfectly in your life, what would you be doing in 10 years?','The concentration area in your brain is like a muscle; breathe and be aware of every breath, once you wonder off in thoughts and notice, come back to the breath. Every time you notice you’ve wandered off and came back; will be the equivalent of a rep in lifting a weight.','A focus on our strengths, urges us toward a desired future and stimulates openness to new ideas, people and plans. In contrast, spotlighting our weaknesses elicits a defensive sense of obligation and guilt, closing us down.','You need negative focus to survive, but a positive to thrive.','Anxiety associated with punishment hampers the prefrontal cortex while trying to concentrate and learn, creating further impediment for improvement.','The core elements of smart practise rely on a combination of joy, tactics and full focus.','Mindfulness of the future means taking into account the consequences of our actions.','To tell a good story; is to grab and keep someone\’s attention.','Leader example - "We don\'t hire to make… we make to hire"','In the service of what am I using the talents I have?','Anger builds on anger; the highest level becomes a point of violence becoming unforgiving and beyond reasoned with. The thoughts revolve on revenge or reprisal, oblivious to what the consequence must be.','Disable your angry opponent before reaching a cognitive incapacitation. ',
'During anger you must not suppress it. But don\'t act on it.','Setting the emotional tone of an interaction means a sign of dominance, it is why emotional entertainment  is the heart of influence.','The greatest things are accomplished by silence - not in the clamor or display of superficial eventfulness, but in the deep clarity of inner vision.','Sometimes it seems that our many words are more an expression of our doubt than our faith.','When the lord is accused he keeps silent. He has no need of defence. Those who defend themselves  are those who fear being defeated.','Speak only when it is more useful to speak than to be silent.','A bitter ending is better than an endless bitterness.','Its not about how hard you hit, its about how hard you get hit and still moving forward.','Only the <b>disciplined</b> ones are free in life. If you aren\'t <b>disciplined</b>, you are a slave to your moods. You are a slave to your passions.','It is only by becoming aware of our vulnerability to social pressure that we can begin to build resistance to conformity when it is not in our best interest to yield to the mentality of the herd.','Nearly all men can stand adversity, but if you want to test a man\’s character, give him power.','Kindness can be more than its own reward.','The power of a situation and the behaviour imposed by a system determines a social context.',
'Every exit is an entrance somewhere else.','Those who have a "why" can bare any "how"','The price of anything is the amount of life you exchange for it.','The law never to be broken is never to be required.','Everyone reacts and therefor consequentially acts to the form they deem most convenient based on their knowledge from life experience, therefor I cannot judge for something I would have comited if placed under the same circumstances of life and its obstacles.','Aim to be the person at your father\'s funeral that everyone, in their grief and misery, can rely on.','The devil learns more from experience than from intellect'

    ]

    cookie3.style.display="none";
var inner_div=document.createElement('div');
var text=document.createElement("p");
text.classList+="innertext"
text.innerHTML=list[num];
console.log(list.length);

inner_div.appendChild(text);
inner_div.classList+="inner-div";
cookie_div3.appendChild(inner_div);    
})
